import React, { useState } from "react";
import { data, useNavigate } from "react-router-dom";
import FAQComponent from "./FAQComponent";
import "../style/CheckGrievanceFeedbackStatus.css";
import VirtualKeyboard from "./VirtualKeyboard";
import { useEffect } from "react";
import { fetchCaptcha } from "../APIs/captchaAPI";
import AudioIcon from "../assets/AudioIcon.svg";
import RefreshIcon from "../assets/RefreshIcon.svg";
import Popup from "./Popup";
import { checkcomplaintStatus } from "../APIs/grievanceStatusAPI";
import { useTranslation } from "react-i18next";

function CheckGrievanceFeedbackStatus() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [showFaqModal, setShowFaqModal] = useState(false);
const [showResult, setShowResult] = useState(false);
const [data, setdata] = useState("");
  const [serviceNumber, setServiceNumber] = useState("");
const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});
  const [focusedInput, setFocusedInput] = useState(null);
const [showKeyboard, setShowKeyboard] = useState(false);
const [captchaInput, setCaptchaInput] = useState("");
const [captchaError, setCaptchaError] = useState("");
  const [showPopup, setShowPopup] = useState(false);
  const [popupMessage, setPopupMessage] = useState("");
const [captchaData, setCaptchaData] = useState({
  img: "",
  audio: "",
  trxId: ""
});

useEffect(() => {
  loadNewCaptcha();
}, []);

const loadNewCaptcha = async () => {
  const result = await fetchCaptcha();

  if (result.success) {
    setCaptchaData({
      img: `data:image/jpeg;base64,${result.base64}`,
      audio: result.audioBase64
        ? `data:audio/wav;base64,${result.audioBase64}`
        : "",
      trxId: result.transactionId
    });
  } else {
    setCaptchaData({
      img: "",
      audio: "",
      trxId: ""
    });
  }

  setCaptchaInput("");
};

const playAudio = () => {
  if (!captchaData.audio) return;

  const audio = new Audio(captchaData.audio);
  audio.play().catch(err =>
    console.error("Audio error:", err)
  );
};

useEffect(() => {
  const hideKeyboard = (e) => {
    if (
      !e.target.closest(".simple-input") &&
      !e.target.closest(".vk-chromeos")
    ) {
      setShowKeyboard(false);
      setFocusedInput(null);
    }
  };

  document.addEventListener("mousedown", hideKeyboard);
  return () => document.removeEventListener("mousedown", hideKeyboard);
}, []);

const handleSubmit = async () => {
  let newErrors = {};

  if (!serviceNumber.trim()) {
    newErrors.serviceNumber = t("serviceNumberRequired");
  }

  if (!captchaInput.trim()) {
    setCaptchaError(t("captchaRequired"));
  }

  if (!captchaData.trxId) {
 setCaptchaError(t("captchaNotLoaded"));
  }

  if (Object.keys(newErrors).length > 0 || !captchaInput.trim()) {
    setErrors(newErrors);
    return;
  }

  try {
    setLoading(true);

    // const payload = {
    //   complaintId: serviceNumber,
    //   captchaTxnId: captchaData.trxId,
    //   captchaValue: captchaInput
    // };

    // 🔹 Replace with your real API call
    // const response = await fetch("/api/check-grievance-status", {
    //   method: "POST",
    //   headers: {
    //     "Content-Type": "application/json"
    //   },
    //   body: JSON.stringify(payload)
    // });
    
    const response = await checkcomplaintStatus({
      complaintId: serviceNumber,
      captchaTxnId: captchaData.trxId,
      captchaValue: captchaInput
    })
    //alert(1);
    console.log(response.data);
    
    if(response.data.status == "success"){
      setServiceNumber("");
      setCaptchaInput("");
      setdata(response.data);
      setShowResult(true);
    }else{   

      setPopupMessage(response.data.errorDetails.messageEnglish);
      setShowPopup(true);
    }
    // SUCCESS
    

  } catch (error) {
   setCaptchaError(t("invalidCaptchaOrService"));
    loadNewCaptcha();   // refresh captcha on error
  } finally {
    setLoading(false);
  }
};
  const faqs = [
  {
    question: "What is the expiry period of VID?",
    answer:
      "At this time there is no expiry period defined for VID. VID will be valid till the time a new VID is generated by the Aadhaar number holder."
  }
];
const handleKeyPress = (key) => {
  if (focusedInput === "serviceNumber") {
    setServiceNumber((prev) => prev + key);
    if (errors.serviceNumber) {
      setErrors({ ...errors, serviceNumber: "" });
    }
  }

  if (focusedInput === "captcha") {
    setCaptcha((prev) => prev + key);
    if (errors.captcha) {
      setErrors({ ...errors, captcha: "" });
    }
  }
};

const handleBackspace = () => {
  if (focusedInput === "serviceNumber") {
    setServiceNumber((prev) => prev.slice(0, -1));
  }

  if (focusedInput === "captcha") {
    setCaptcha((prev) => prev.slice(0, -1));
  }
};

const handleClear = () => {
  if (focusedInput === "serviceNumber") {
    setServiceNumber("");
  }

  if (focusedInput === "captcha") {
    setCaptcha("");
  }
};

  return (
    <div className="full-screen-center-validity">
        {showPopup && (
                      <Popup
                        message={popupMessage}
                        onClose={() => setShowPopup(false)}
                      />
                    )}
     <div className="aadhaar-wrapper">


        {/* Header */}
     <div className="uidai-header-val position-relative">
  

  <div className="uidai-header-left d-flex align-items-center">
   <span className="ms-3">
  {t("checkGrievanceStatus")}
</span>
          </div>
            <button
                           className="kiosk-back-circle-validity header-back-btn"
              onClick={() => navigate("/kiosk-home2")}
            >
              ⬅
            </button>
         
        </div>

        {/* Card */}
        <div className="row eaadhaar-page">
          <div className="col-12">
            <div className="card grievance-card shadow-sm p-4 position-relative">

              {/* FAQ Button */}
              <div className="d-flex justify-content-end mb-3">
                <button
                  className="help-btn"
                  onClick={() => setShowFaqModal(true)}
                >
                  <span className="help-icon-aadhar-validity">?</span>
                </button>
              </div>

              {/* Service Request Number */}
              <div className="form-group mb-4">
                <label className="form-label text-muted labelText">
             {t("enterServiceRequestNumber")}
                </label>
                <input
  type="text"
  className={`simple-input ${errors.serviceNumber ? "is-invalid" : ""}`}
  value={serviceNumber}
  onChange={(e) => setServiceNumber(e.target.value)}
  onFocus={() => {
    setFocusedInput("serviceNumber");
    setShowKeyboard(true);
  }}
/>
                {errors.serviceNumber && (
                  <div className="text-danger mt-1">
                    {errors.serviceNumber}
                  </div>
                )}
              </div>

                   <div className="row align-items-center captcha-row">
           
                           <div className="col-12 col-md-6">
                             <label className="form-label text-muted labelText">
                           {t("enterCaptcha")}
                             </label>
      <input
  type="text"
  className={`simple-input ${captchaError ? "is-invalid" : ""}`}
  value={captchaInput}
  onChange={(e) => {
    setCaptchaInput(e.target.value);
    if (captchaError) setCaptchaError("");
  }}
  onFocus={() => {
    setFocusedInput("captcha");
    setShowKeyboard(true);
  }}
/>

{captchaError && (
  <div className="text-danger small mt-1">
    {captchaError}
  </div>
)}
           
           {captchaError && (
             <div className="text-danger small mt-1">
               {captchaError}
             </div>
           )}
           
                           </div>
           
                           <div className="col-12 col-md-6">
                             <div className="captcha-display d-flex align-items-center gap-2 bg-light p-2 rounded">
           
                               <div style={{
                                 background: "#fff",
                                 padding: "2px",
                                 border: "1px solid #ddd",
                                 minWidth: "100px",
                                 height: "35px",
                                 display: "flex",
                                 justifyContent: "center"
                               }}>
                                 {captchaData.img ? (
                                   <img
                                     src={captchaData.img}
                                     alt="Captcha"
                                     style={{ height: "100%" }}
                                   />
                                 ) : (
                                   <span style={{ fontSize: "10px" }}>Loading...</span>
                                 )}
                               </div>
           
                               <button
                                 type="button"
                                 className="captcha-btn"
                                 onClick={playAudio}
                                 disabled={!captchaData.audio}
                               >
                                 <img src={AudioIcon} alt="Audio" />
                               </button>
           
                           <button
             type="button"
             className="captcha-btn"
             onClick={() => {
               setCaptchaInput("");
               loadNewCaptcha();
             }}
           >
             <img src={RefreshIcon} alt="Refresh" />
           </button>
           
           
                             </div>
                           </div>
           
                         </div>
           
              {/* Submit Button */}
              <div className="mt-4">
               <button
  className="submit-btn"
  onClick={handleSubmit}
  disabled={loading}
>
  {loading ? (
    <span className="loader-spinner"></span>
  ) : (
  t("submit")
  )}
</button>
              </div>
              {showResult && (
  <div className="mt-4 grievance-result-card">

    <div className="result-header d-flex justify-content-between">
   <span>{t("grievanceFeedbackNumber")}</span>
      <strong>{data?.responseData?.interactionid}</strong>
    </div>

    <div className="result-body mt-3">
      
        {
          data?.responseData?.qrcs?.map((item,index)=>
          (
            <><div className="d-flex justify-content-between mb-2">
           <span>{t("status")}</span>
              <strong>{item.status}</strong>
            </div><p className="result-text">
                {item.acknowledgement_response}
              </p></>
          ))
        }

      
    </div>

  </div>
)}

            </div>
          </div>
        </div>
      </div>

    {showFaqModal && (
  <div className="faq-modal-backdrop">
    <div className="faq-modal">
      <div className="faq-modal-header-validity">
     <h5>{t("frequentlyAskedQuestions")}</h5>
        <button
          className="close-btn"
          onClick={() => setShowFaqModal(false)}
        >
          ✕
        </button>
      </div>

      <div className="faq-modal-body">
        <FAQComponent faqs={faqs} />
      </div>
    </div>
  </div>
)}
<VirtualKeyboard
  visible={showKeyboard}
  onKeyPress={handleKeyPress}
  onBackspace={handleBackspace}
  onClear={handleClear}
  onClose={() => {
    setShowKeyboard(false);
    setFocusedInput(null);
  }}
/>
    </div>
  );
}

export default CheckGrievanceFeedbackStatus;