import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import FAQComponent from "./FAQComponent";
import VirtualKeyboard from "./VirtualKeyboard";
import { useEffect } from "react";
import { fetchCaptcha } from "../APIs/captchaAPI";
import AudioIcon from "../assets/AudioIcon.svg";
import RefreshIcon from "../assets/RefreshIcon.svg";
import { getcategoryList } from "../APIs/getgrievancecategoryAPI";
import { useTranslation } from "react-i18next";

function Grievancefeedback() {
    const navigate = useNavigate();
    const [data, setData] = useState({});
    const [showFaqModal, setShowFaqModal] = useState(false);
    const [focusedInput, setFocusedInput] = useState(null);
    const [showKeyboard, setShowKeyboard] = useState(false);
    const [errors, setErrors] = useState({});
    const [captchaInput, setCaptchaInput] = useState("");
    const [captchaError, setCaptchaError] = useState("");
    const [loading, setLoading] = useState(false);
    const [category, setcategory] = useState("");
    const { t } = useTranslation();
   const [selectedSubCategory, setSelectedSubCategory] = useState(null);
  const [selectedCategory, setSelectedCategory] = useState(null);
    const [captchaData, setCaptchaData] = useState({
        img: "",
        audio: "",
        trxId: ""
    });
    const loadNewCaptcha = async () => {
        const result = await fetchCaptcha();

        if (result.success) {
            setCaptchaData({
                img: `data:image/jpeg;base64,${result.base64}`,
                audio: result.audioBase64
                    ? `data:audio/wav;base64,${result.audioBase64}`
                    : "",
                trxId: result.transactionId
            });
        } else {
            setCaptchaData({
                img: "",
                audio: "",
                trxId: ""
            });
        }

        setCaptchaInput("");
    };
     const handleCategoryChange = (categoryObj) => {
  setSelectedCategory(categoryObj);
};
    const loadCategoryList = async () => {
        const result = await getcategoryList();
        console.log(result)
        if (result.data.status === "success") {
          setData(result.data.responseData);
        }

        setCaptchaInput("");
    };
    useEffect(() => {
        loadCategoryList();
    }, []);
    useEffect(() => {
        loadNewCaptcha();
    }, []);
    
    useEffect(() => {
        const hideKeyboard = (e) => {
            if (
                !e.target.closest(".simple-input") &&
                !e.target.closest(".vk-chromeos")
            ) {
                setShowKeyboard(false);
                setFocusedInput(null);
            }
        };

        document.addEventListener("mousedown", hideKeyboard);
        return () => document.removeEventListener("mousedown", hideKeyboard);
    }, []);

    const playAudio = () => {
        if (!captchaData.audio) return;

        const audio = new Audio(captchaData.audio);
        audio.play().catch(err =>
            console.error("Audio error:", err)
        );
    };
    const [formData, setFormData] = useState({
        name: "",
        mobile: "",
        email: "",
        state: "",
        grievanceFor: "",
        grievanceType: "",
        categoryType: "",
        grievanceText: "",
        captcha: "",
          updatedField: "",
    srn: "",
    eid: "",
    urn: "",

    enrolDate: "",
    enrolTime: ""

    });

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };
    const faqs = [
        {
            question: "What is the expiry period of VID?",
            answer:
                "At this time there is no expiry period defined for VID. VID will be valid till the time a new VID is generated by the Aadhaar number holder."
        }

    ];
    const handleKeyPress = (key) => {
        if (!focusedInput) return;

        setFormData((prev) => {
            let value = prev[focusedInput] + key;

            if (focusedInput === "mobile") {
                value = value.replace(/\D/g, "").slice(0, 10);
            }

            if (focusedInput === "name") {
                value = value.replace(/[^a-zA-Z\s]/g, "").slice(0, 60);
            }

            return {
                ...prev,
                [focusedInput]: value
            };
        });
    };

    const handleBackspace = () => {
        if (!focusedInput) return;

        setFormData((prev) => ({
            ...prev,
            [focusedInput]: prev[focusedInput].slice(0, -1)
        }));
    };

    const handleClear = () => {
        if (!focusedInput) return;

        setFormData((prev) => ({
            ...prev,
            [focusedInput]: ""
        }));
    };
    const validateForm = () => {
        let newErrors = {};

        if (!formData.name.trim())
         newErrors.name = t("nameRequired");

        if (!formData.mobile.trim())
          newErrors.mobile = t("mobileRequired");
        else if (!/^\d{10}$/.test(formData.mobile))
        newErrors.mobile = t("mobileInvalid");

        if (formData.email) {
            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            if (!emailRegex.test(formData.email))
               newErrors.email = t("emailInvalid");
        }
        if (!captchaInput.trim())
            newErrors.captcha = "Captcha is required";

        if (!captchaData.trxId)
            newErrors.captcha = "Captcha not loaded";

        if (!formData.state)
        newErrors.state = t("stateRequired");

        if (!formData.grievanceFor)
    newErrors.grievanceFor = t("grievanceForRequired");

        if (!formData.grievanceType)
          newErrors.grievanceType = t("grievanceTypeRequired");

        if (!formData.categoryType)
       newErrors.categoryType = t("categoryRequired");

        if (!formData.grievanceText.trim())
         newErrors.grievanceText = t("grievanceTextRequired");

        if (!formData.captcha.trim())
          newErrors.captcha = t("captchaRequired");

        setErrors(newErrors);

        return Object.keys(newErrors).length === 0;
    };
    const handleSubmit = async () => {
        const isValid = validateForm();
        if (!isValid) return;

        setLoading(true);   // 🔹 Start Loader

        try {
            const payload = {
                captchaTxnId: captchaData.trxId,
                captcha: captchaInput
            };

            // 🔴 Call your backend API
            // await validateCaptcha(payload);

            const generatedSRN = "S" + Date.now();

            navigate("/grievance-success", {
                state: { srn: generatedSRN }
            });

        } catch (error) {
            setCaptchaError("Invalid Captcha");
            loadNewCaptcha();
        } finally {
            setLoading(false);   // 🔹 Stop Loader
        }
    };
     const grievanceTypesWithOptions = [
  "Authentication Issue",
  "Update Related",
  "NEET / CUET and other Competitive exam",
  "Aadhaar Letter / PVC Status"
];
const grievancePlaceholder = selectedCategory?.required
  ? "Please provide: " + selectedCategory.required.join(", ")
  : "Enter your grievance details here...";


    return (
        <div className="full-screen-center">
  <div className="aadhaar-wrapper">
              <div className="uidai-header position-relative">
  

  <div className="uidai-header-left d-flex align-items-center">
             <span className="ms-3">{t("grievanceFeedback")}</span>    </div>
                        <button
                           className="kiosk-back-circle header-back-btn"
                            onClick={() => navigate("/kiosk-home2")}
                        >
                            ⬅
                        </button>

             
                </div>

                <div className="row eaadhaar-page">
                    <div className="col-12">
                        <div className="card shadow-sm p-4">
                            {/* HELP BUTTON */}
                            <div className="d-flex justify-content-end mb-3">
                                <button
                                    className="help-btn"
                                    onClick={() => setShowFaqModal(true)}
                                >
                                    <span className="help-icon">?</span>
                                </button>
                            </div>

                       <h5 className="mb-3">{t("enterRequiredDetails")}</h5>

                            {/* Name */}
                            <div className="mb-3">
                                <label className="form-label text-muted labelText">{t("enterName")}</label>
                                <input
                                    type="text"
                                    className="simple-input"
                                    name="name"
                                    maxLength={60}
                                    autoComplete="off"
                                    value={formData.name}
                                    onChange={handleChange}
                                    onFocus={() => {
                                        setFocusedInput("name");
                                        setShowKeyboard(true);
                                    }}

                                />
                                {errors.name && (
                                    <div className="text-danger small mt-1">
                                        {errors.name}
                                    </div>
                                )}
                            </div>

                            {/* Mobile */}
                            <div className="mb-3">
                                <label className="form-label text-muted labelText">{t("enterMobile")}</label>
                                <input
                                    type="text"
                                    className="simple-input"
                                    name="mobile"
                                    maxLength={10}
                                    autoComplete="off"
                                    value={formData.mobile}
                                    onChange={handleChange}
                                    onFocus={() => {
                                        setFocusedInput("mobile");
                                        setShowKeyboard(true);
                                    }}
                                />
                                {errors.mobile && (
                                    <div className="text-danger small mt-1">
                                        {errors.mobile}
                                    </div>
                                )}
                            </div>

                            {/* Email */}
                            <div className="mb-3">
                                <label className="form-label text-muted labelText">{t("enterEmail")}</label>
                                <input
                                    type="email"
                                    className={`simple-input ${errors.email ? "is-invalid" : ""}`}
                                    name="email"
                                    autoComplete="off"
                                    value={formData.email}
                                    onChange={handleChange}
                                    onFocus={() => {
                                        setFocusedInput("email");
                                        setShowKeyboard(true);
                                    }}
                                />

                                {errors.email && (
                                    <div className="text-danger small mt-1">
                                        {errors.email}
                                    </div>
                                )}
                            </div>

                            {/* State */}
                            <div className="mb-3">
                                <label className="form-label text-muted labelText">{t("enterState")}</label>
                                <select
                                    className={`simple-input ${errors.state ? "is-invalid" : ""}`}
                                    name="state"
                                    value={formData.state}
                                    onChange={handleChange}
                                >

                                    <option value="">{t("selectState")}</option>
                                    <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                                    <option value="Andhra Pradesh">Andhra Pradesh</option>
                                    <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                                    <option value="Assam">Assam</option>
                                    <option value="Bihar">Bihar</option>
                                    <option value="Chandigarh">Chandigarh</option>
                                    <option value="Chhattisgarh">Chhattisgarh </option>
                                    <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
                                    <option value="Daman and Diu">Daman and Diu</option>
                                    <option value="Delhi">Delhi </option>
                                    <option value="Goa">Goa</option>
                                    <option value="Gujarat">Gujarat</option>
                                    <option value="Haryana">Haryana </option>
                                    <option value="Himachal Pradesh">Himachal Pradesh</option>
                                    <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                                    <option value="Jharkhand">Jharkhand </option>
                                    <option value="Karnataka">Karnataka</option>
                                    <option value="Kerala">Kerala</option>
                                    <option value="Lakshadweep">Lakshadweep </option>
                                    <option value="Madhya Pradesh">Madhya Pradesh</option>
                                    <option value="Maharashtra">Maharashtra</option>
                                    <option value="Manipur">Manipur </option>
                                    <option value="Meghalaya">Meghalaya</option>
                                    <option value="Mizoram">Mizoram</option>
                                    <option value="Nagaland">Nagaland </option>
                                    <option value="Odisha">Odisha</option>
                                    <option value="Puducherry">Puducherry</option>
                                    <option value="Punjab">Punjab </option>
                                    <option value="Rajasthan">Rajasthan</option>
                                    <option value="Sikkim">Sikkim</option>
                                    <option value="Tamil Nadu">Tamil Nadu </option>
                                    <option value="Telangana">Telangana</option>
                                    <option value="Tripura">Tripura</option>
                                    <option value="Uttar Pradesh">Uttar Pradesh </option>
                                    <option value="Uttarakhand">Uttarakhand</option>
                                    <option value="West Bengal">West Bengal</option>
                                </select>
                                {errors.state && (
                                    <div className="text-danger small mt-1">
                                        {errors.state}
                                    </div>
                                )}
                            </div>

                            {/* Grievance For */}
                            <div className="mb-3">
                                <label className="form-label text-muted labelText">
                                   {t("grievanceFor")}
                                </label>
                                <select
                                    className={`simple-input ${errors.grievanceFor ? "is-invalid" : ""}`}
                                    name="grievanceFor"
                                    value={formData.grievanceFor}
                                    onChange={handleChange}
                                >
                                    <option value="">{t("select")}</option>
                                    <option value="Self">Self</option>
                                    <option value="Other">Others</option>
                                </select>
                                {errors.grievanceFor && (
                                    <div className="text-danger small mt-1">
                                        {errors.grievanceFor}
                                    </div>
                                )}
                            </div>

                                          <div className="mb-3">
                <label className="form-label text-muted labelText">
                {t("grievanceType")}
                </label>                     {/* Grievance Type */}
                <select
                  className="simple-input"
                  name="grievanceType"
                  value={formData.grievanceType}
                  onChange={(e) => {
                    const selectedType = e.target.value;

                    setFormData((prev) => ({
                      ...prev,
                      grievanceType: selectedType,
                      categoryType: ""
                    }));

                    setSelectedSubCategory(null);
                  }}
                >
                  <option value="">{t("select")}</option>

                  {Object.keys(data || {}).map((key) => (
                    <option key={key} value={key}>
                      {key}
                    </option>
                  ))}
                </select>
              </div>              
              <div className="mb-3">
                <label className="form-label text-muted labelText">
             {t("categoryType")}
                </label>

                <select
                  className="simple-input"
                  name="categoryType"
                  value={formData.categoryType}
                  onChange={(e) => {
                    const selectedShortcode = e.target.value;

                    const selectedObj =
                      data[formData.grievanceType]?.categories?.find(
                        (item) => item.shortcode === selectedShortcode
                      );

                    setSelectedSubCategory(selectedObj || null);

                    setFormData((prev) => ({
                      ...prev,
                      categoryType: selectedShortcode
                    }));
                  }}
                  disabled={!formData.grievanceType}
                >
                  <option value="">{t("categoryType")}</option>

                  {formData.grievanceType &&
                    data[formData.grievanceType]?.categories?.map((item) => (
                      <option key={item.shortcode} value={item.shortcode}>
                        {item.label}
                      </option>
                    ))}
                </select>
              </div>

            
{grievanceTypesWithOptions.includes(formData.grievanceType) && (
  <div className="mb-4">
    <label className="form-label labelText">
{t("mode")}
    </label>

    <div className="radio-group d-flex gap-4 flex-wrap">
      {[
        {
  value: "online",
  label: t("online"),
  help: t("onlineHelp")
},
        {
          value: "offline",
          label:t("offline"),
          help: t("offlineHelp")
        },
        {
          value: "mAadhaar mobile App",
          label: t("maadhaar"),
          help: t("maadhaarHelp")
        }
      ].map((option, index) => (
        <div key={index} className="radio-wrapper">
          <label className="custom-radio">
            <input
              type="radio"
              name="updatedField"
              value={option.value}
              checked={formData.updatedField === option.value}
              onChange={(e) =>
                setFormData({
                  ...formData,
                  updatedField: e.target.value,
                  srn: "",
                  eid: "",
                  urn: "",
                  enrolDate: "",
                  enrolTime: ""
                })
              }
            />
            <span className="radio-circle"></span>
            <span className="radio-text">{option.label}</span>
          </label>

          {/* Helper Text */}
          <div className="radio-help-text">
            {option.help}
          </div>
        </div>
      ))}
    </div>
  </div>
)}

             
            {formData.updatedField === "online" && (
  <div className="mb-3">
    <label className="form-label text-muted labelText">
    {t("enterSRN")}
    </label>

    <input
      type="text"
      className="simple-input"
      value={formData.srn}
      onChange={(e) => {
        let value = e.target.value.toUpperCase();

        // Always force first character as S
        if (!value.startsWith("S")) {
          value = "S" + value.replace(/^S*/i, "");
        }

        setFormData({ ...formData, srn: value });
      }}
      placeholder="S000000000000"
    />
  </div>
)}
              {formData.updatedField === "offline" && (
                <>
                  {/* EID */}
                  <div className="mb-3">
                    <label className="form-label text-muted labelText">
              {t("enterEID")}
                    </label>
                    <input
                      type="text"
                      className="simple-input"
                      value={formData.eid}
                      maxLength={14}
                      onChange={(e) =>
                        setFormData({
                          ...formData,
                          eid: e.target.value.replace(/\D/g, "")
                        })
                      }
                    />
                  </div>

                  {/* Date */}
                  <div className="mb-3 underline-input">
                    <label className="form-label text-muted labelText">
                {t("selectDate")}
                    </label>
                    <input
                      type="date"
                      className="simple-input"
                      value={formData.enrolDate || ""}
                      onChange={(e) =>
                        setFormData({
                          ...formData,
                          enrolDate: e.target.value
                        })
                      }
                    />
                  </div>

                  {/* Time */}
                  <div className="mb-3 underline-input">
                    <label className="form-label text-muted labelText">
                 {t("selectTime")}
                    </label>
                    <input
                      type="time"
                      className="simple-input"
                      value={formData.enrolTime || ""}
                      onChange={(e) =>
                        setFormData({
                          ...formData,
                          enrolTime: e.target.value
                        })
                      }
                    />
                  </div>
                </>
              )}
              {formData.updatedField === "mAadhaar mobile App" && (
                <div className="mb-3">
                  <label className="form-label text-muted labelText">
                 {t("enterURN")}

                  </label>
                  <input
                    type="text"
                    className="simple-input"
                      maxLength={8}
                    value={formData.urn}
                    onChange={(e) =>
                      setFormData({ ...formData, urn: e.target.value })
                    }
                  />
                </div>
              )}

              {/* File Upload */}
              <div className="mb-3">
                <label className="form-label text-muted labelText">
             {t("supportingDocument")}
                </label>
                <input type="file" className="form-control" />
              </div>
{/* Required Info Display Above Textarea */}
{selectedSubCategory?.required && (
  <div
    className="mb-3 p-3 rounded"
    style={{
      backgroundColor: "#b7cadd",   // light grey
      border: "1px solid #dee2e6"
    }}
  >
 

    <ul className="small mb-0 ps-3">
      {selectedSubCategory.required.map((field, index) => (
        <li key={index}>{field}</li>
      ))}
    </ul>
  </div>
)}

{/* Main Textarea */}
<div className="mb-3">


  <textarea
    className="form-control simple-input grievance-textarea"
    name="grievanceText"
    value={formData.grievanceText}
    autoComplete="off"
    onChange={handleChange}
    onFocus={() => {
      setFocusedInput("grievanceText");
      setShowKeyboard(true);
    }}

  ></textarea>

  {errors.grievanceText && (
    <div className="text-danger small mt-1">
      {errors.grievanceText}
    </div>
  )}
</div>
            


                            {/* Captcha */}
                            <div className="row align-items-center captcha-row">

                                <div className="col-12 col-md-6">
                                    <label className="form-label text-muted labelText">
                                        {t("enterCaptcha")}
                                    </label>
                                    <input
                                        type="text"
                                        className={`simple-input ${errors.captcha ? "is-invalid" : ""}`}
                                        value={captchaInput}
                                        onChange={(e) => {
                                            setCaptchaInput(e.target.value);
                                            if (errors.captcha) {
                                                setErrors({ ...errors, captcha: "" });
                                            }
                                        }}
                                        onFocus={() => {
                                            setFocusedInput("captcha");
                                            setShowKeyboard(true);
                                        }}
                                    />

                                    {errors.captcha && (
                                        <div className="text-danger small mt-1">
                                            {errors.captcha}
                                        </div>
                                    )}

                                    {captchaError && (
                                        <div className="text-danger small mt-1">
                                            {captchaError}
                                        </div>
                                    )}

                                </div>

                                <div className="col-12 col-md-6">
                                    <div className="captcha-display d-flex align-items-center gap-2 bg-light p-2 rounded">

                                        <div style={{
                                            background: "#fff",
                                            padding: "2px",
                                            border: "1px solid #ddd",
                                            minWidth: "100px",
                                            height: "35px",
                                            display: "flex",
                                            justifyContent: "center"
                                        }}>
                                            {captchaData.img ? (
                                                <img
                                                    src={captchaData.img}
                                                    alt="Captcha"
                                                    style={{ height: "100%" }}
                                                />
                                            ) : (
                                                <span style={{ fontSize: "10px" }}>Loading...</span>
                                            )}
                                        </div>

                                        <button
                                            type="button"
                                            className="captcha-btn"
                                            onClick={playAudio}
                                            disabled={!captchaData.audio}
                                        >
                                            <img src={AudioIcon} alt="Audio" />
                                        </button>

                                        <button
                                            type="button"
                                            className="captcha-btn"
                                            onClick={() => {
                                                setCaptchaInput("");
                                                loadNewCaptcha();
                                            }}
                                        >
                                            <img src={RefreshIcon} alt="Refresh" />
                                        </button>


                                    </div>
                                </div>

                            </div>

                            {/* Buttons */}
                            <div className="d-flex justify-content-between mt-5">
                                <button
                                    className="btn btn-outline-primary"
                                    onClick={() => navigate(-1)}
                                >
                                    {t("back")}
                                </button>
<button
  className="btn btn-secondary"
  onClick={handleSubmit}
  disabled={loading}
>
  {loading ? (
    <>
      <span
        className="spinner-border spinner-border-sm me-2"
        role="status"
        aria-hidden="true"
      ></span>
      {t("pleaseWait")}
    </>
  ) : (
    t("next")
  )}
</button></div>
                        </div>
                    </div>
                </div>
                {/* FAQ MODAL */}
                {showFaqModal && (
                    <div className="faq-modal-backdrop">
                        <div className="faq-modal">
                            <div className="faq-modal-header">
                                <h5>{t("faqTitle")}</h5>
                                <button
                                    className="close-btn"
                                    onClick={() => setShowFaqModal(false)}
                                >
                                    ✕
                                </button>
                            </div>
                            <div className="faq-modal-body">
                                <FAQComponent faqs={faqs} />
                            </div>
                        </div>
                    </div>
                )}

                <VirtualKeyboard
                    visible={showKeyboard}
                    onKeyPress={handleKeyPress}
                    onBackspace={handleBackspace}
                    onClear={handleClear}
                    onClose={() => {
                        setShowKeyboard(false);
                        setFocusedInput(null);
                    }}
                />

            </div>
        </div>
    );
}

export default Grievancefeedback;